import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body 
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20">

                    <Header />

                    <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
                        {children}

                    </main>

                    <Footer />

                </div>

            </body>
        </html>
    );
}